### PR TITLE
add bidding flow

### PR DESCRIPTION
**Pull request by dingsheng-ong**
Added flow to fetch market data from RSE API:
image
Requires [aimlac-7564616D/composer#19](https://github.com/aimlac-7564616D/composer/pull/19)

Scheduled to place bids at 0845 every morning:
image

### CODE REVIEW

**Review by fjebaker — APPROVED** [review]
LGTM

**Comment by fjebaker** [comment]
It's a little hard to tell, but I take it the "http request" node is making the request to the flask server to get the data? I can see you make a request to `aimlac-models` so I am assuming this is the case.

**Comment by fjebaker** [comment]
Also, without having had a proper look at the source code, will this flow work beyond bogo bid too?

**Comment by dingsheng-ong** [comment]
> Also, without having had a proper look at the source code, will this flow work beyond bogo bid too?

I can't say for sure but most probably it will work if the new bidder function is implemented appropriately.

**Pull request merged**
